language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
env:
  matrix:
    - LARAVEL='^5.5'
    - LARAVEL='^5.5' COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL='^6.0'
    - LARAVEL='^6.0' COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL='^7.0'
    - LARAVEL='^7.0' COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL='^8.0'
    - LARAVEL='^8.0' COMPOSER_FLAGS="--prefer-lowest"
    - LARAVEL='^9.0'
    - LARAVEL='^9.0' COMPOSER_FLAGS="--prefer-lowest"
install:
  - composer require "laravel/framework:${LARAVEL}" --prefer-dist --no-interaction --no-suggest ${COMPOSER_FLAGS}
  - composer install --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
